fix: release version with github short hash

diff --git a/.github/workflows/aws-build.yml b/.github/workflows/aws-build.yml
--- a/.github/workflows/aws-build.yml
+++ b/.github/workflows/aws-build.yml
@@ -115,6 +115,7 @@ jobs:
         shell: bash
         run: |
           SERVICE_NAME=$(cat .infra/infra-config.json | jq .name | tr -d '"')
+          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_OUTPUT;
           if [[ $BRANCH_NAME == "master" && ${{ github.event_name }} != "workflow_dispatch" ]]; then \
             echo "PROJECT=$(echo $SERVICE_NAME-production)" >> $GITHUB_ENV; \
             echo "stage=production" >> $GITHUB_OUTPUT; \
@@ -162,31 +163,42 @@ jobs:
           echo "CODEBUILD_PROJECT=$CODEBUILD" >> $GITHUB_ENV;
           echo $CODEBUILD_PROJECT
 
-      # - name: Configure AWS Credentials - Shared
-      #   if: contains(fromJson('["push", "release", "pull_request", "workflow_dispatch"]'), github.event_name)
-      #   uses: aws-actions/configure-aws-credentials@v2
-      #   with:
-      #     aws-access-key-id: ${{ secrets.SHARED_AWS_ACCESS_KEY_ID }}
-      #     aws-secret-access-key: ${{ secrets.SHARED_AWS_SECRET_ACCESS_KEY }}
-      #     aws-region: ${{ secrets.SHARED_AWS_REGION }}
+      - name: Configure AWS Credentials - Shared
+        if: contains(fromJson('["push", "release", "pull_request", "workflow_dispatch"]'), github.event_name)
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.SHARED_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.SHARED_AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.SHARED_AWS_REGION }}
 
-      # - name: Check ECR image tag
-      #   continue-on-error: true
-      #   run: |
-      #     ECR_REPOSITORY=$(aws ecr describe-repositories --region us-east-2 --query 'repositories[?ends_with(repositoryName, `ms-budgets`) == `true`]' | jq ".[0].repositoryName" | tr -d '"')
-      #     aws ecr describe-images --repository-name $ECR_REPOSITORY --image-ids imageTag=${{ steps.set_project_name.outputs.release_version}}
-      
-      # - name: Configure AWS Credentials - CICD
-      #   if: contains(fromJson('["push", "release", "pull_request", "workflow_dispatch"]'), github.event_name)
-      #   uses: aws-actions/configure-aws-credentials@v2
-      #   with:
-      #     aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
-      #     aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
-      #     aws-region: ${{ secrets.CICD_AWS_REGION }}
+      - name: Check ECR image tag
+        id: check-ecr-tag
+        run: |
+          ECR_REPOSITORY=$(aws ecr describe-repositories --region ${{ secrets.SHARED_AWS_REGION }} --query 'repositories[?ends_with(repositoryName, `${{ steps.set_project_name.outputs.SERVICE_NAME}}`) == `true`]' | jq ".[0].repositoryName" | tr -d '"')
+          echo "ECR Repository: "$ECR_REPOSITORY
+          aws ecr describe-images --repository-name $ECR_REPOSITORY --region ${{ secrets.SHARED_AWS_REGION }} --image-ids imageTag=${{ steps.set_project_name.outputs.release_version}}
+          exit_status=$?
+          
+          # Check the exit status
+          if [ $exit_status -eq 0 ]; then
+            echo "Release version is already builded"
+            echo "ecr_image_exist=true" >> $GITHUB_OUTPUT;
+          else
+            echo "Release version is not builded"
+            echo "ecr_image_exist=false" >> $GITHUB_OUTPUT;
+          fi
+
+      - name: Configure AWS Credentials - CICD
+        if: contains(fromJson('["push", "release", "pull_request", "workflow_dispatch"]'), github.event_name)
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.CICD_AWS_REGION }}
 
       - name: Run AWS CodeBuild
         id: codebuild
-        if: contains(fromJson('["true"]'), steps.check-project.outputs.project_exist ) && contains(fromJson('["push", "release", "workflow_dispatch"]'), github.event_name)
+        if: contains(fromJson('["true"]'), steps.check-project.outputs.project_exist ) && contains(fromJson('["push", "release", "workflow_dispatch"]'), github.event_name) && !steps.check-ecr-tag.outputs.ecr_image_exist
         uses: dark-mechanicum/aws-codebuild@v1
         env:
           CODEBUILD__sourceVersion: ${{ env.BRANCH_NAME }}
